export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'
export const STORE_MESSAGE = 'STORE_MESSAGE'
export const STORE_SESSION = 'STORE_SESSION'
